feat: 2.1 preparations (#1876)
* Release preparations

* Fix workflow warning

* Fix test with hardcoded index version

* fix: executable permissions

* feat: improved error message for unknown predefined variables in env (#1875)

Now full message mentions the fact that this evaluation is expected for
prededefined variables and the offending key is printed.

Example:
```
error: Unknown predefined variable in environment variable 'PATH' of 'alr': Unknown formatting key: HOME
```

* fix: assorted bitrot since last release

* fix: Windows installer

---------

Co-authored-by: Manuel <mgrojo@gmail.com>